### ISSUE TITLE
[BUG]traits and storage trigger

### ISSUE THREAD

**Issue by xr0master** [artf/grapesjs#1092]
Hey, maybe it's not bug, i'm not sure.

I have traits with changeProp: true field.
When I change the value of trait by UI, model is changed and all works fine, but the new changes aren't saved in Storage. So, after refresh the editor, I miss the values. If I append any component, when Storage is triggered and all have been saved.

Thank you for your amazing project.

**Comment by artf** [comment]
Should be fixed by this https://github.com/artf/grapesjs/commit/32c1b2c1f4e1bef967f43b0013bfd481cddb81c7

**Comment by xr0master** [comment]
Nope. It doesn't fix it.

**Comment by xr0master** [comment]
Probably the #1104 close to fix it

**Comment by xr0master** [comment]
The jsfiddle example from 1104 with a new trait, the value didn't save.
Added the custom component
Selected the added component
Switched to Settings tab
Input the Default Value
Refreshed
....................
The value didn't save

https://jsfiddle.net/Lqm7ouze/3/

**Comment by simeiyu** [comment]
Why do I still encounter this problem when I use version 0.14.55?
