### ISSUE TITLE
BUG: with buttons

### ISSUE THREAD

**Issue by OleksandrNeroda** [artf/grapesjs#3205]
https://grapesjs.com/demo.html

when i edit the button text to 'test'
after reload the result: 
![image](https://user-images.githubusercontent.com/14879734/102893138-55630000-4461-11eb-9ca8-7918610915aa.png)

**Comment by OleksandrNeroda** [comment]
@artf  maybe you can help with this?

**Comment by Swindler36** [comment]
This demo saves your changes to your local storage of the browser. If you didn't save, it is normal. Try to save or run `editor.store()` in console.

**Comment by OleksandrNeroda** [comment]
@Swindler36 in my project i do not use the local storage only everything is saved to the database, but the problem the same. I don't think that is a local storage problem.

**Comment by Swindler36** [comment]
I wanted to say that if you didn't save your changes to your storage, after the page refresh it loads older save. Therefore, you can try to save your changes before reloading.

**Comment by OleksandrNeroda** [comment]
ok but that's weird. Why is this problem only for the button? You tried to recreate it on https://grapesjs.com/demo.html 
old and new values are concatenated after refreshing

**Comment by artf** [comment]
Fixed with the new release of the form plugin https://github.com/artf/grapesjs-plugin-forms/releases/tag/v2.0.1

**Comment by OleksandrNeroda** [comment]
@artf However, from what I can see in the version v0.16.34 at https://grapesjs.com/demo.html it is still possible to reproduce this bug.

**Comment by artf** [comment]
sorry @OleksandrNeroda I'm too lazy to update also the demo with the new version 😂  PR is welcome

**Comment by dan-castillo** [comment]
I believe this is still happening with version 0.17.28 see the attached image
![image](https://user-images.githubusercontent.com/32414569/141467583-92b520f7-9c17-48e6-b360-ba926c0c1ebd.png)
