### ISSUE TITLE
[Question]: Doctype in the canvas iframe

### ISSUE THREAD

**Issue by ashercoren** [artf/grapesjs#3285]
Hi.
This question has already been asked twice ([here](https://github.com/artf/grapesjs/issues/973) and [here](https://github.com/artf/grapesjs/issues/1230)) but has never got an answer.

Is there a way to add `<!DOCTYPE html>` as the beginning of the canvas iframe so that the iframe will be in standards mode.

I need this since I am trying to use tinyMce as the custom RTE, and tinyMce requires standards mode.

**Comment by artf** [comment]
Not really, but I'm open to solutions on how to make it customizable.

**Comment by krishnaeverestengineering** [comment]
Me also facing similar issue. We are using tinymce 4 for now, but need to upgrade it to tinymce 5. Can somebody provide us thoughts?

**Comment by artf** [comment]
In the next release, I'll add a new event helper that will allow editing iframe content before load:
```js
editor.on('frame:load:before', ({ el }) => {
  const doc = el.contentDocument;
  doc.open();
  doc.write("<!DOCTYPE html>");
  doc.close();
});
```

**Comment by bryanjamesmiller** [comment]
> In the next release, I'll add a new event helper that will allow editing iframe content before load:
> 
> ```js
> editor.on('frame:load:before', ({ el }) => {
>   const doc = el.contentDocument;
>   doc.open();
>   doc.write("<!DOCTYPE html>");
>   doc.close();
> });
> ```

I'd be interested to hear if others have successfully implemented this, because when we implement this solution @artf it breaks the ability for us to drag blocks onto the canvas area of Grapes.  We are on Grapes version 0.17.29.

**Comment by krishnaeverestengineering** [comment]
Hey @bryanjamesmiller . We have implemented it. Can you share your implementation?

**Comment by krishnaeverestengineering** [comment]
@bryanjamesmiller  can you please add **draggableComponents** property in the configuration and check.

**Comment by krishnaeverestengineering** [comment]
You can set this in configuration 

**domComponents: {
    draggableComponents: false
}**

**Comment by bryanjamesmiller** [comment]
@krishnaeverestengineering Thank you for the suggestion.  I tried it with your suggestion but it did not fix it; however, I was able to replicate this issue on JSFiddle using the example from the docs at https://grapesjs.com/docs/getting-started.html#add-blocks - all I had to do was add the code block I pasted above.  You can see the issue must not have to do with our implementation unless there is something wrong with the snipped I posted above.  Here is the JSFiddle - https://jsfiddle.net/f4ga0rte/ - **please note you have to delete all blocks already present in the canvas for the issue to appear**.

**Comment by bryanjamesmiller** [comment]
@krishnaeverestengineering I've made a video demo of the problem:  https://watch.screencastify.com/v/HYOmCVLvUXQObkq2baTL

**Comment by bryanjamesmiller** [comment]
This issue is reminiscent of another issue folks were having https://github.com/artf/grapesjs/issues/116 as it appears easier to reproduce on Firefox than Chrome

**Comment by bryanjamesmiller** [comment]
@artf is there a reason for not including doctype by default?

**Comment by bryanjamesmiller** [comment]
Here is a simple demo of the issue I am running into:  https://jsfiddle.net/gratiafide/mgfetw95/5/  cc @krishnaeverestengineering  @artf
